### ISSUE TITLE
strategy to fire polymorphic rules

### ISSUE THREAD

**Issue by andyczerwonka** [krzemin/octopus#51]
I'm evaluating Octopus and am unable to model a couple of use cases, so I'm wondering if I'm just "doing it wrong".

- An ability to define a rule on an trait of abstract type and derive the rules across the type hierarchy. I don't think is supported, or at least the [shapes example](https://github.com/krzemin/octopus/blob/master/octopus/src/test/scala/octopus/example/domain/Shapes.scala) doesn't exercise it.
- Map field names to errors. I think I'm just missing something, as the documentation explicitly suggests that this case should work by default.

All four of the following tests fail:

```scala
class OctopusValidationTest extends BaseUnitTest {

  import octopus.syntax._
  import octopus.dsl._

  trait HasName {
    val name: String
  }
  sealed trait Pet extends HasName
  object Pet {
    implicit val nameIsRequiredAndCantStartWithZ: Validator[Pet] = Validator[Pet]
      .rule(_.name.nonEmpty, "is required")
      .rule(_.name.startsWith("Z"), "can't start with Z")
  }

  case class Dog(name: String) extends Pet
  object Dog {
    implicit val allDogsMustBeNamedRooney: Validator[Dog] = Validator[Dog]
      .rule(_.name == "Rooney", "is not Rooney")
  }

  case class Cat(name: String) extends Pet
  object Cat {
    implicit val allCatNamesLessThanFive: Validator[Cat] = Validator[Cat]
      .rule(_.name.length < 5, "is too long")
  }

  def validate[T <: Pet: Validator](pet: T) = pet.validate.toFieldErrMapping

  // this test fails because the error is ("","is not Rooney")
  test("dogs name is not rooney") {
    val notRooney = Dog("Bart")
    val errors = validate(notRooney)
    errors should have size 1
    errors should contain theSameElementsAs List(
      ("name", "is not Rooney")
    )
  }

  // this test fails because the error is ("","is too long")
  test("cats name is too long") {
    val rumpelstiltskin = Cat("Rumpelstiltskin")
    val errors = validate(rumpelstiltskin)
    errors should have size 1
    errors should contain theSameElementsAs List(
      ("name", "is too long")
    )
  }

  // this only tests concrete rule, how do we trigger the pet rule?
  test("pets name isEmpty and not Rooney") {
    val emptyDog = Dog("")
    validate(emptyDog) should have size 2
  }

  // this only tests concrete rule, how do we trigger the pet rule?
  test("cats name is too long and starts with Z") {
    val zumpelstiltskin = Cat("Zumpelstiltskin")
    validate(zumpelstiltskin) should have size 2
  }
}
```

**Comment by krzemin** [comment]
Hey,

Yes, that's the current limitation that error paths are carried only when you define implicit validator on a certain type. Note that `Validator.rule` can take arbitrary predicate as first parameter and there's no any magic for sub path reconstruction implemented.

If you want to have your paths carried properly with errors, recommended approach is to use value classes and define validations for specific types.

```scala
case class Name(value: String) extends AnyVal
trait HasName {
    val name: Name
}

case class Dog(name: Name) extends Pet


test("dogs name is not rooney") {
    implicit val nameValidator: Validator[Name] = Validator[Name]
      .rule(_.value == "Rooney", "is not Rooney")

    val notRooney = Dog(Name("Bart"))
    val errors = validate(notRooney)
    errors should have size 1
    errors should contain theSameElementsAs List(
      ("name", "is not Rooney")
    )
}
```

> An ability to define a rule on an trait of abstract type and derive the rules across the type hierarchy. I don't think is supported, or at least the shapes example doesn't exercise it.

Although I know it's not properly tested or documented, that should be supported. You can summon supertype validator with `Validator.derive[Base]` and when defining validator for a subtype, you can compose it with base validator using `composeSuper`.

**Comment by andyczerwonka** [comment]
@krzemin Ok, understood on the property values. Unfortunate, but I can see why it's difficult to support otherwise.

In terms of the type hierarchy, for some reason, I tried `derive[Pet]` but it won't compile. Getting `value derived is not a member of octopus.Validator[OctopusValidationTest.this.Pet]`

Can you give and example? Once I get that part working, I'll issue a PR of the README docs.

**Comment by krzemin** [comment]
> Unfortunate, but I can see why it's difficult to support otherwise.

Oh, there is [3-arg rule](https://github.com/krzemin/octopus/blob/8f75b2e001f8e8b0ffd0bed38d0671d7bd8d2f63/octopus/src/main/scala/octopus/dsl.scala#L39) which takes path as a first argument. This is also how you can provide path information to your validation errors.

> Is there a way to compose with all implicit validators in scope for type Pet?

You can have only a single validator for a specific type in the implicit scope. This is inherent limitation of implicit scope in Scala ;)

**Comment by andyczerwonka** [comment]
So there is no reason to use `derived[Pet]` for my use case? I don't quite grok when I need that.

> You can have only a single validator for a specific type in the implicit scope. This is inherent limitation of implicit scope in Scala ;)
Of course, silly me.

> there is 3-arg rule which takes path as a first argument. This is also how you can provide path information to your validation errors.
Is there an example somewhere?

**Comment by andyczerwonka** [comment]
@krzemin As an elaboration to the above, I've create a test where I want to validate a data structure that contains `Pet`s.

```scala
  case class Family(name: String, pets: Seq[Pet])
  object Family {
    implicit val validations: Validator[Family] = Validator[Family]
      .rule(_.name, (_: String).nonEmpty, "is required")
      .composeDerived
  }
```
When I test this case:

```scala
  test("a family with a few pets") {
    val failingPets = List(Cat("Zumpelstiltskin"), Dog(""))
    val family = Family("", failingPets)
    val errors = validate(family)
    errors should have size 5
  }
```
In that case, I only get the rules associated directly with the `family` and `Pet` trait. Is there a way to wire this up so that I can the rules fired for the concrete types?

**Comment by krzemin** [comment]
This is because you already have validator for `Pet` in your implicit scope, so the library rules that support sealed families can't enter into the play.

You can do 2 things:
1) remove `composeSuper`, use `Validator.derive[Pet]` and enhance it with your base type rules (https://scastie.scala-lang.org/7MuyBzUcRdOfYPz9xWx05Q)
2) don't define implicit validator for base type (it will be automatically derived), but compose your common rules into each subtype validator (https://scastie.scala-lang.org/CO3XgG6xQGOadyuleS57zg)

The first approach is quite cleaner in terms of implementation, but it has disadvantage that depending on cast context  (`Pet` or `Dog`), you end up with different validation ruleset. It's fixed by explicit composition in the second version.

**Comment by andyczerwonka** [comment]
@krzemin Yes, the second approach is fine. It does find the concrete rules. The following test now passes.

```scala
  test("a family with a few pets") {
    val failingPets = List(Cat("Zumpelstiltskin"), Dog(""))
    val family = Family("", Dog("Rooney"), failingPets)
    val errors = validate(family)
    errors should have size 5
    errors should contain theSameElementsAs List(
      ("otherPets[0].name", "can't start with Z"),
      ("otherPets[0].name", "is too long"),
      ("otherPets[1].name", "is required"),
      ("otherPets[1].name", "is not Rooney"),
      ("name", "is required")
    )
  }
```
It would be nice to be able to construct the message using the object for each rule. I think I saw a feature request around that.

**Comment by andyczerwonka** [comment]
I think the spirit of this ticket is now resolved. Thanks @krzemin !

**Comment by andyczerwonka** [comment]
@krzemin one more question in the context of this ticket. I have take my test case and applying learnings to another code base, and I am getting the following compiler error:

```
could not find implicit value for parameter dv: octopus.DerivedValidator[io.andyczerwonka.model.Design]
                       [error]     .derived[Design]
                       [error]            
```
But I do have an implicit parameter. I have to derive here, because the `Design` contains a `Set` of other objects that need to be validated.

```scala
object Design {
  implicit val validations: Validator[Design] = Validator
    .derived[Design]
    .composeSuper(Space.baseValidations)
}
```
I don't see a material difference from my examples (other than it being a single file). What should I be looking for here to chase down my error?

**Comment by krzemin** [comment]
> `could not find implicit value for parameter dv: octopus.DerivedValidator[io.andyczerwonka.model.Design]`

That's the issue when having an implicit derivation based on shapeless - you don't really get descriptive error messages.

When `.derived[...]` says it can't find implicit `DerivedValidator`, it means it probably can't derive it for one of the fields. Try to eliminate (comment out) fields one by one to narrow the problem. Maybe using `Set` or `Map` here and there is problematic?

It could be helpful if you would provide base types definitions (and their companion object validators). Maybe even create a runnable Scastie, so that'd be easier to play around?

**Comment by andyczerwonka** [comment]
> When .derived[...] says it can't find implicit DerivedValidator, it means it probably can't derive it for one of the fields. Try to eliminate (comment out) fields one by one to narrow the problem. 

Cool, I'll try that and see which field is causing it. There aren't many.

**Comment by andyczerwonka** [comment]
Found it, `data` used a `HashMap` in the API, that it fails on that type.

**Comment by andyczerwonka** [comment]
@krzemin This use case popped up again, this time with a more difficult solution. See https://github.com/krzemin/octopus/issues/59
