### ISSUE TITLE
writing a rule using multiple fields

### ISSUE THREAD

**Issue by andyczerwonka** [krzemin/octopus#55]
Given the following data structure

```scala
  case class Family(name: String, children: Set[Child], mainPet: Pet, otherPets: Seq[Pet])
  object Family {
    implicit val validations: Validator[Family] = Validator
      .derived[Family]
      .rule[String](_.name, _.nonEmpty, "is required")
  }
```

Is there a way to write a rule that combines more than one field? E.g.

- `mainPet` can't be the same as one of the `otherPet`s
- `mainPet` name can't be the same as one of the `children`s' name

I tried writing a `selector` that would map a tuple, e.g. `Family => (String, Pet)`, but it looks like [the macro won't support that](https://github.com/krzemin/octopus/blob/master/octopus/src/main/scala/octopus/DslMacros.scala#L7-L33).

```scala
val familyNameCantBeSameAsMainPet = (pair: (String, Pet)) => pair._1 != pair._2.name
val nameAndMainPetSelector = (family: Family) => (family.name, family.mainPet)
...
...
.rule[(String, Pet)](nameAndMainPetSelector, familyNameCantBeSameAsMainPet, "testing tuple selector")
```

**Comment by krzemin** [comment]
I don't think there is a reasonable way to have a single rule assigned to multiple field selectors.
Either choose one selector, on use selector-less (2-args) `rule(...)` variant, that just addresses the whole `Family`. Note that even selector-less rule will have proper path (to a family object) in any nested context.

**Comment by andyczerwonka** [comment]
> use selector-less (2-args) rule(...) variant, that just addresses the whole Family. Note that even selector-less rule will have proper path (to a family object) in any nested context.

@krzemin Dang! It didn't occur to me to select the whole family. Now, I did write a rule:

```scala
  case class Family(name: String, children: Set[Child], mainPet: Pet, otherPets: Seq[Pet])
  object Family {
    val familyLevelRule = (family: Family) => family.name != family.mainPet.name
    implicit val validations: Validator[Family] = Validator
      .derived[Family]
      .rule(_.name, (_: String).nonEmpty, "is required")
      .rule(familyLevelRule, "name cannot be the same as pet name")
  }
```
But the test has an empty path. See below, the test passes with an empty path. Last line of the test.

```scala
  test("family name can't be the same as the main pet") {
    val children = Set(Child("Sara", 21), Child("Nick", 17))
    val family = Family("Rooney", Set.empty, Dog("Rooney"), Seq.empty)
    val errors = validate(family)
    errors should have size 1
    errors should contain theSameElementsAs List(
      ("", "name cannot be the same as pet name")
    )
  }
```

**Comment by krzemin** [comment]
Well, empty path here means root path. So in this context I believe it's correct as for such validation the problem is due to invalid relationship between different field values.

When you have Family nested (or in a collection), you get your family-level errors prefixed with non empty path.

If you really need to, you can assign this error to a single specific field (name? using 3 arg rule). Other options are not supported currently.

**Comment by andyczerwonka** [comment]
> If you really need to, you can assign this error to a single specific field (name? using 3 arg rule).

@krzemin how would I do that? The selector is `T => F` and the rule predicate is  `F => Boolean`. So it I select `_.name` as the selector, I have to write `String => Boolean`, but I want `Family => Boolean`.

**Comment by krzemin** [comment]
Sorry, my bad. You can't do this currently using library's rules. You would need to have a rule with signature like:

```scala
 def rule[F](selector: T => F, pred: T => Boolean, whenInvalid: String): Validator[T]
```

Which should quite be straightforward to implement, but it would need to be named differently.

**Comment by andyczerwonka** [comment]
We can throw this one on the roadmap as a feature request for custom naming. Closing.
